name: studyplan_repository
description: "A studyplan repository package"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #equitable
  equatable: ^2.0.5
  #bloc
  #flutter_bloc: ^8.1.6
  #firebase
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4

  #Custom Repository
  user_repository:
    path: ../user_repository
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
